version: '3.5'
services:
  web:
    image: nginx:1.19.1-alpine
    restart: always
    ports:
      - "80:80"
    working_dir: /usr/share/nginx/html
    volumes:
      - ./docs:/usr/share/nginx/html
    labels:
      com.dnsdock.alias: ncvvaldelsa.loc
    environment:
      - NGINX_HOST=ncvvaldelsa.loc
      - NGINX_PORT=80
