web:
  image: nginx:latest
  hostname: ncvvaldelsa
  environment:
    - DNSDOCK_ALIAS=ncvvaldelsa.loc
  restart: always
  ports:
    - "80:80"
  volumes:
    - ./web:/usr/share/nginx/html
    - ./nginx_site.conf:/etc/nginx/conf.d/nginx_site.conf

php:
  image: php:7-fpm
  volumes:
    - ./web:/usr/share/nginx/html
